"""empty message

Revision ID: 108081b2a563
Revises: 
Create Date: 2024-10-21 23:40:52.418927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108081b2a563'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
