"""Initial migration

Revision ID: 1f73ef06ea61
Revises: 
Create Date: 2024-11-04 18:47:26.474336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f73ef06ea61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint('assets_migration_id_fkey', type_='foreignkey')
        batch_op.drop_column('migration_id')

    with op.batch_alter_table('migration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'assets', ['asset_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('migration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('asset_id')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('migration_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('assets_migration_id_fkey', 'migration', ['migration_id'], ['id'])

    # ### end Alembic commands ###
