"""empty message

Revision ID: 81f44ee6e45a
Revises: 60672fad3cf9
Create Date: 2024-10-28 20:02:40.116563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f44ee6e45a'
down_revision = '60672fad3cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('engineer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'provider', ['provider_id'], ['id'])

    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.drop_constraint('provider_engineer_id_fkey', type_='foreignkey')
        batch_op.drop_column('engineer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engineer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('provider_engineer_id_fkey', 'engineer', ['engineer_id'], ['id'])

    with op.batch_alter_table('engineer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('provider_id')

    # ### end Alembic commands ###
