"""empty message

Revision ID: 9b9a42ca43db
Revises: 7e7042fc2ba0
Create Date: 2024-10-28 16:45:08.414830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9a42ca43db'
down_revision = '7e7042fc2ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_code', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('asset_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('asset_description', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('asset_status', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['asset_code'])
        batch_op.drop_constraint('assets_engineer_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('assets_admins_id_fkey', type_='foreignkey')
        batch_op.drop_column('engineer_id')
        batch_op.drop_column('asset_inventory_number')
        batch_op.drop_column('asset_brand')
        batch_op.drop_column('asset_type')
        batch_op.drop_column('admins_id')
        batch_op.drop_column('asset_serial')
        batch_op.drop_column('asset_model')

    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('branch_code', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('branch_branch_cr_key', type_='unique')
        batch_op.drop_constraint('branch_engineer_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('branch_admins_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('branch_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('engineer_id')
        batch_op.drop_column('branch_cr')
        batch_op.drop_column('user_id')
        batch_op.drop_column('branch_category')
        batch_op.drop_column('branch_address')
        batch_op.drop_column('branch_zone')
        batch_op.drop_column('branch_saturday')
        batch_op.drop_column('admins_id')
        batch_op.drop_column('branch_subzone')
        batch_op.drop_column('branch_work_stations')

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('history_link_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('history_asset_id_fkey', type_='foreignkey')
        batch_op.drop_column('asset_id')
        batch_op.drop_column('link_id')
        batch_op.drop_column('date')
        batch_op.drop_column('message')

    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=250), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('speed')
        batch_op.drop_column('type')
        batch_op.drop_column('status')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('provider_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('branch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('message')

    with op.batch_alter_table('migration', schema=None) as batch_op:
        batch_op.drop_constraint('migration_engineer_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('migration_branch_id_fkey', type_='foreignkey')
        batch_op.drop_column('engineer_id')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('user_mb', schema=None) as batch_op:
        batch_op.drop_constraint('user_mb_employee_number_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_mb', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_mb_employee_number_key', ['employee_number'])

    with op.batch_alter_table('migration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('engineer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('migration_branch_id_fkey', 'branch', ['branch_id'], ['id'])
        batch_op.create_foreign_key('migration_engineer_id_fkey', 'engineer', ['engineer_id'], ['id'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.alter_column('branch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('provider_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('body')
        batch_op.drop_column('subject')

    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('speed', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
        batch_op.drop_column('url')

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('link_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('history_asset_id_fkey', 'assets', ['asset_id'], ['id'])
        batch_op.create_foreign_key('history_link_id_fkey', 'link', ['link_id'], ['id'])
        batch_op.drop_column('timestamp')
        batch_op.drop_column('action')

    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_work_stations', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('branch_subzone', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('admins_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('branch_saturday', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('branch_zone', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('branch_address', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('branch_category', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('branch_cr', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('engineer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('branch_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('branch_admins_id_fkey', 'admins', ['admins_id'], ['id'])
        batch_op.create_foreign_key('branch_engineer_id_fkey', 'engineer', ['engineer_id'], ['id'])
        batch_op.create_unique_constraint('branch_branch_cr_key', ['branch_cr'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('branch_code')
        batch_op.drop_column('branch_name')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_model', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('asset_serial', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('admins_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('asset_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('asset_brand', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('asset_inventory_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('engineer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('assets_admins_id_fkey', 'admins', ['admins_id'], ['id'])
        batch_op.create_foreign_key('assets_engineer_id_fkey', 'engineer', ['engineer_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('asset_status')
        batch_op.drop_column('asset_description')
        batch_op.drop_column('asset_name')
        batch_op.drop_column('asset_code')

    # ### end Alembic commands ###
