"""empty message

Revision ID: 9e9890b1aee8
Revises: 6b946d5a6c23
Create Date: 2024-10-26 18:18:28.508379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9890b1aee8'
down_revision = '6b946d5a6c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('migration_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'migration', ['migration_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('migration_id')

    # ### end Alembic commands ###
