"""empty message

Revision ID: c25c9051c813
Revises: ac1d537b7123
Create Date: 2024-10-24 19:33:10.544240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25c9051c813'
down_revision = 'ac1d537b7123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))

    with op.batch_alter_table('engineer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('engineer', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
