"""empty message

Revision ID: eeeb7f177aee
Revises: 81f44ee6e45a
Create Date: 2024-10-28 20:39:02.248801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeeb7f177aee'
down_revision = '81f44ee6e45a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_mb_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_mb', ['user_mb_id'], ['id'])

    with op.batch_alter_table('user_mb', schema=None) as batch_op:
        batch_op.drop_constraint('user_mb_asset_id_fkey', type_='foreignkey')
        batch_op.drop_column('asset_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_mb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_mb_asset_id_fkey', 'assets', ['asset_id'], ['id'])

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_mb_id')

    # ### end Alembic commands ###
